[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpa-calculator"
version = "0.0.1"
authors = [
  { name="Pete Dives", email="pdives@msudenver.edu" },
]
description = "Computes credit-weighted GPA from a list of grade/credit entries."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/FrostyBagels/SWD_Proj1"
"Bug Tracker" = "https://github.com/FrostyBagels/SWD_Proj1"