@startuml class
left to right direction

class Course {
    - prefix: String
    - number: String
    - name: String
    - credits: Int
}

class Enrollment{
    - user_id: String
    - course_prefix: String
    - course_number: String
    - grade: String

}

class User {
    - name: String
    - id: String
    - about: String
    - passwd: Binary
}

User "1" -- "0..*" Enrollment
Course "1" -- "0..*" Enrollment

@enduml
