@startuml use_case
:Student:
:User:

User <|-- Student
package "Student GPA System" {
    :User: --> (Logs in)
    :Student: --> (Logs in)
    :Student: --> (Past Courses) 
    (Past Courses) .. (Current GPA) : includes
    :Student: --> (Current Courses)
    :Student: --> (Current GPA)
    :Student: --> (Grade Update)
    :Student: --> (Grade deletion)
    (Past Courses) .. (Grade Deletion) : extends
    (Past Courses) .. (Grade Update) : extends

}
@enduml