@startuml use_case
:Student:


package "Student GPA System" {
    :Student: --> (sign up)
    :Student: --> (log in)
    :Student: --> (sign out)
    :Student: --> (view enrollments)
    :Student: --> (view GPA)
    :Student: --> (adds enrollment)
    :Student: --> (updates grade)
    :Student: --> (deletes enrollment)
    
    (view enrollments) .. (view GPA) : includes
    (adds enrollment) .. (GPA updates) : includes
    (updates grade) .. (GPA updates) : includes
    (deletes enrollment) .. (GPA updates) : includes
}
@enduml