[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpacalculator3250"
version = "0.0.1"
authors = [
  { name="Pete Dives", email="pdives@msudenver.edu" },
  { name="Tyler Black", email="tblack11@msudenver.edu" },
  { name="Stephanie Rivera", email="sriver49@msudenver.edu" },
  { name="Cameron Greeson", email="cgreeson@msudenver.edu" },
]
description = "Computes credit-weighted GPA from a list of grade/credit entries."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/FrostyBagels/SWD_Proj1"
"Bug Tracker" = "https://github.com/FrostyBagels/SWD_Proj1"